targetCustomizations:
- name: prod
  helm:
    values:
      serviceType: ClusterIP
      replicas: 2
      namespace: "${ .ClusterLabels.vehicleid }-ammysore"
  clusterSelector:
    matchLabels:
      env: vehicle
