namespace: "${ .ClusterLabels.vehicleid }-service1"
targetCustomizations:
- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 2
      namespace: "${ .ClusterLabels.vehicleid }-service1"
  clusterSelector:
    matchLabels:
      env: vehicle
