defaultNamespace: "vehicle-service2"
helm:
  releaseName: "${ .ClusterLabels.vehicleid }-service2"
targetCustomizations:
- name: prod
  helm:
    values:
      serviceType: ClusterIP
      replicas: 2
      namespace: "${ .ClusterLabels.vehicleid }-service1"
  clusterSelector:
    matchLabels:
      env: vehicle
